### PR TITLE
rename + adds docs

### PR DESCRIPTION
**Pull request by nhejazi**
This PR adds several new and important changes, summarized as follows

* renaming of the package from `mangolassi` to `hal9001`
* adds documentation for most (all?) C++ functions exported for `Rcpp`

### CODE REVIEW

**Comment by jeremyrcoyle** [comment]
Tagging @wilsoncai1992 to make him aware of the name change

**Comment by nhejazi** [comment]
Thanks for merging!

@wilsoncai1992 -- be aware that the name change affects the _package_ and not the _repo_, so re-installing and loading the package would work as follows:
```r
devtools::install_github("jeremyrcoyle/mangolassi")
library(hal9001)
```

**Comment by jeremyrcoyle** [comment]
I just changed the repo name to match

**Comment by wilsoncai1992** [comment]
truly appreciate it!

**Pull request merged**
